name: release

on:
  release:
    types:
      - created

jobs:
  generate:
    name: Generate wasm build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate build files
        uses: lukebaal/build-ffprobe-wasm-with-docker@master

      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./ffprobe-wasm.tar.gz"
